# Generated by Django 5.1.15 on 2026-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_phase9_admin_cms_marketing_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="name_ar",
            field=models.CharField(
                help_text="Display name of the city, e.g. Doha.",
                max_length=120,
                null=True,
                verbose_name="City name",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="name_en",
            field=models.CharField(
                help_text="Display name of the city, e.g. Doha.",
                max_length=120,
                null=True,
                verbose_name="City name",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="name_ar",
            field=models.CharField(max_length=120, null=True, verbose_name="Country name"),
        ),
        migrations.AddField(
            model_name="country",
            name="name_en",
            field=models.CharField(max_length=120, null=True, verbose_name="Country name"),
        ),
        migrations.AddField(
            model_name="deliveryslot",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="deliveryslot",
            name="name_ar",
            field=models.CharField(
                help_text="Display label, e.g. Morning 9am–12pm.",
                max_length=80,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="deliveryslot",
            name="name_en",
            field=models.CharField(
                help_text="Display label, e.g. Morning 9am–12pm.",
                max_length=80,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="deliveryzone",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="deliveryzone",
            name="name_ar",
            field=models.CharField(max_length=120, null=True, verbose_name="Zone name"),
        ),
        migrations.AddField(
            model_name="deliveryzone",
            name="name_en",
            field=models.CharField(max_length=120, null=True, verbose_name="Zone name"),
        ),
    ]
