# Generated by Django 5.1.15 on 2026-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_alter_homepagesection_section_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="body_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="body_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="excerpt_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="excerpt_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_description_ar",
            field=models.CharField(
                blank=True,
                help_text="HTML meta description for search engines (max ~160 characters).",
                max_length=160,
                null=True,
                verbose_name="Meta description",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_description_en",
            field=models.CharField(
                blank=True,
                help_text="HTML meta description for search engines (max ~160 characters).",
                max_length=160,
                null=True,
                verbose_name="Meta description",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_title_ar",
            field=models.CharField(
                blank=True,
                help_text="HTML <title> tag content (max ~70 characters).",
                max_length=70,
                null=True,
                verbose_name="Meta title",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_title_en",
            field=models.CharField(
                blank=True,
                help_text="HTML <title> tag content (max ~70 characters).",
                max_length=70,
                null=True,
                verbose_name="Meta title",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="faqitem",
            name="answer_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="faqitem",
            name="answer_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="faqitem",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="faqitem",
            name="question_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="faqitem",
            name="question_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="title_ar",
            field=models.CharField(
                blank=True,
                help_text="Used as the media alt text for accessibility and SEO.",
                max_length=200,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Used as the media alt text for accessibility and SEO.",
                max_length=200,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="config_ar",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Configuration"
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="config_en",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Configuration"
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="title_ar",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="title_en",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="page",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="body_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="body_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_description_ar",
            field=models.CharField(
                blank=True,
                help_text="HTML meta description for search engines (max ~160 characters).",
                max_length=160,
                null=True,
                verbose_name="Meta description",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_description_en",
            field=models.CharField(
                blank=True,
                help_text="HTML meta description for search engines (max ~160 characters).",
                max_length=160,
                null=True,
                verbose_name="Meta description",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_title_ar",
            field=models.CharField(
                blank=True,
                help_text="HTML <title> tag content (max ~70 characters).",
                max_length=70,
                null=True,
                verbose_name="Meta title",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_title_en",
            field=models.CharField(
                blank=True,
                help_text="HTML <title> tag content (max ~70 characters).",
                max_length=70,
                null=True,
                verbose_name="Meta title",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="title_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="body_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="body_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="meta_description_ar",
            field=models.CharField(
                blank=True,
                help_text="HTML meta description for search engines (max ~160 characters).",
                max_length=160,
                null=True,
                verbose_name="Meta description",
            ),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="meta_description_en",
            field=models.CharField(
                blank=True,
                help_text="HTML meta description for search engines (max ~160 characters).",
                max_length=160,
                null=True,
                verbose_name="Meta description",
            ),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="meta_title_ar",
            field=models.CharField(
                blank=True,
                help_text="HTML <title> tag content (max ~70 characters).",
                max_length=70,
                null=True,
                verbose_name="Meta title",
            ),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="meta_title_en",
            field=models.CharField(
                blank=True,
                help_text="HTML <title> tag content (max ~70 characters).",
                max_length=70,
                null=True,
                verbose_name="Meta title",
            ),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="title_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
