# Generated by Django 5.1.15 on 2026-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0003_alter_giftcard_options_alter_giftcard_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashsale",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="flashsale",
            name="name_ar",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="flashsale",
            name="name_en",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
