# Generated by Django 5.1.15 on 2026-07-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phase9_admin_cms_marketing_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='email',
            field=models.CharField(blank=True, db_index=True, help_text='Email the OTP was sent to (email-based purposes only).', max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='Phone number the OTP was sent to.', max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('signup', 'Sign Up'), ('password_reset', 'Password Reset'), ('email_login', 'Email Login')], db_index=True, help_text='Reason this OTP was issued.', max_length=20, verbose_name='Purpose'),
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['email', 'purpose', 'is_used'], name='accounts_otp_email_purpose_idx'),
        ),
    ]
