# Generated by Django 5.1.15 on 2026-07-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otprequest_email_alter_otprequest_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
