# Generated by Django 5.1.15 on 2026-07-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_phase6_cart_checkout_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='guest_details',
            field=models.JSONField(blank=True, default=dict, help_text='Name/contact/address captured for guest checkout (no saved Address row).', verbose_name='Guest details'),
        ),
    ]
