# Generated by Django 5.1.15 on 2026-07-17 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gifting', '0002_giftcustomizationsnapshot_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated at')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='Object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_card_eligibilities', to='contenttypes.contenttype', verbose_name='Content type')),
                ('greeting_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_card_eligibilities', to='gifting.greetingcarddesign', verbose_name='Greeting card')),
            ],
            options={
                'verbose_name': 'Gift card eligibility',
                'verbose_name_plural': 'Gift card eligibilities',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='gifting_card_elig_ct_obj_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'greeting_card'), name='gifting_card_eligibility_unique')],
            },
        ),
        migrations.CreateModel(
            name='GiftPhotoUploadEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated at')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='Object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_photo_eligibilities', to='contenttypes.contenttype', verbose_name='Content type')),
                ('photo_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_photo_eligibilities', to='gifting.giftphotouploadoption', verbose_name='Photo upload option')),
            ],
            options={
                'verbose_name': 'Photo upload eligibility',
                'verbose_name_plural': 'Photo upload eligibilities',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='gifting_photo_elig_ct_obj_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'photo_upload'), name='gifting_photo_eligibility_unique')],
            },
        ),
        migrations.CreateModel(
            name='GiftWrapEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated at')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='Object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_wrap_eligibilities', to='contenttypes.contenttype', verbose_name='Content type')),
                ('gift_wrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_wrap_eligibilities', to='gifting.giftwrapoption', verbose_name='Gift wrap option')),
            ],
            options={
                'verbose_name': 'Gift wrap eligibility',
                'verbose_name_plural': 'Gift wrap eligibilities',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='gifting_wrap_elig_ct_obj_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'gift_wrap'), name='gifting_wrap_eligibility_unique')],
            },
        ),
        migrations.CreateModel(
            name='RibbonEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated at')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='Object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ribbon_eligibilities', to='contenttypes.contenttype', verbose_name='Content type')),
                ('ribbon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ribbon_eligibilities', to='gifting.ribbonoption', verbose_name='Ribbon option')),
            ],
            options={
                'verbose_name': 'Ribbon eligibility',
                'verbose_name_plural': 'Ribbon eligibilities',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='gifting_ribbon_elig_ct_obj_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'ribbon'), name='gifting_ribbon_eligibility_unique')],
            },
        ),
    ]
