# Generated by Django 5.1.15 on 2026-07-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0003_giftcardeligibility_giftphotouploadeligibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftwrapoption',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ribbonoption',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
