# Generated by Django 5.1.15 on 2026-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifting", "0004_alter_giftwrapoption_name_alter_ribbonoption_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftphotouploadoption",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="giftphotouploadoption",
            name="name_ar",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="giftphotouploadoption",
            name="name_en",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="giftwrapoption",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="giftwrapoption",
            name="name_ar",
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="giftwrapoption",
            name="name_en",
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="greetingcarddesign",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="greetingcarddesign",
            name="name_ar",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="greetingcarddesign",
            name="name_en",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="ribbonoption",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="ribbonoption",
            name="name_ar",
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="ribbonoption",
            name="name_en",
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name="Name"),
        ),
    ]
