# Generated by Django 5.1.15 on 2026-07-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0004_alter_giftwrapoption_name_alter_ribbonoption_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcustomizationsnapshot',
            name='uploaded_photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='gifting/customer_photos/', verbose_name='Uploaded photo file'),
        ),
    ]
