# Generated by Django 5.1.15 on 2026-07-30 18:20

import gifting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifting", "0006_merge_20260730_2347"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcustomizationsnapshot",
            name="uploaded_photo_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="gifting/customer_photos/",
                validators=[gifting.models.validate_image_size],
                verbose_name="Uploaded photo file",
            ),
        ),
    ]
