# Generated by Django 5.1.15 on 2026-07-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_recipient_product_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(max_length=50, verbose_name='Variant type'),
        ),
    ]
