# Generated by Django 5.1.15 on 2026-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_productvariant_variant_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "variant_type", "name")},
        ),
        migrations.AddField(
            model_name="brand",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="name_ar",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="brand",
            name="name_en",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="category",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description_ar",
            field=models.CharField(
                blank=True, max_length=160, null=True, verbose_name="Meta description"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description_en",
            field=models.CharField(
                blank=True, max_length=160, null=True, verbose_name="Meta description"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_title_ar",
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name="Meta title"),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_title_en",
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name="Meta title"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ar",
            field=models.CharField(
                help_text="Display name of the category.",
                max_length=120,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                help_text="Display name of the category.",
                max_length=120,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="occasion",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="occasion",
            name="name_ar",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="occasion",
            name="name_en",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="product",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="color_ar",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Primary color for PLP color-filter chips.",
                max_length=50,
                null=True,
                verbose_name="Color",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="color_en",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Primary color for PLP color-filter chips.",
                max_length=50,
                null=True,
                verbose_name="Color",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description_ar",
            field=models.CharField(
                blank=True, max_length=160, null=True, verbose_name="Meta description"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description_en",
            field=models.CharField(
                blank=True, max_length=160, null=True, verbose_name="Meta description"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title_ar",
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name="Meta title"),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title_en",
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name="Meta title"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ar",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_text_ar",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Alt text"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_text_en",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Alt text"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="name_ar",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="name_en",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="recipient",
            name="ar_translation_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                db_index=True,
                default="auto",
                help_text="Automatic: Arabic is kept in sync from English. Manual: Arabic is never overwritten by the translator.",
                max_length=16,
                verbose_name="Arabic translation source",
            ),
        ),
        migrations.AddField(
            model_name="recipient",
            name="name_ar",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="recipient",
            name="name_en",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={
                ("product", "variant_type", "name"),
                ("product", "variant_type", "name_ar"),
                ("product", "variant_type", "name_en"),
            },
        ),
    ]
