# Generated by Django 5.1.15 on 2026-07-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_content_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Storefront product description shown on the PDP.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, help_text='Storefront product description shown on the PDP.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, help_text='Storefront product description shown on the PDP.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='preparation_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated preparation time in minutes before dispatch.', null=True, verbose_name='Preparation minutes'),
        ),
    ]
